//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUET_SGIPC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;
    public partial class Gallery
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Path { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
